// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteCallRequest.proto

package balmysundaycandy.scalatool.shared;

public final class RemoteCallRequest {
  private RemoteCallRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CallRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use CallRequest.newBuilder() to construct.
    private CallRequest() {
      initFields();
    }
    private CallRequest(boolean noInit) {}
    
    private static final CallRequest defaultInstance;
    public static CallRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CallRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return balmysundaycandy.scalatool.shared.RemoteCallRequest.internal_static_balmysundaycandy_scalatool_shared_CallRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return balmysundaycandy.scalatool.shared.RemoteCallRequest.internal_static_balmysundaycandy_scalatool_shared_CallRequest_fieldAccessorTable;
    }
    
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      RUN_SERVICE_CALL(0, 0),
      RUN_REMOTE_CALL(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static RequestType valueOf(int value) {
        switch (value) {
          case 0: return RUN_SERVICE_CALL;
          case 1: return RUN_REMOTE_CALL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final RequestType[] VALUES = {
        RUN_SERVICE_CALL, RUN_REMOTE_CALL, 
      };
      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private RequestType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        balmysundaycandy.scalatool.shared.RemoteCallRequest.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:balmysundaycandy.scalatool.shared.CallRequest.RequestType)
    }
    
    // required .balmysundaycandy.scalatool.shared.CallRequest.RequestType requestType = 1;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private boolean hasRequestType;
    private balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType requestType_;
    public boolean hasRequestType() { return hasRequestType; }
    public balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType getRequestType() { return requestType_; }
    
    // optional string serviceName = 2;
    public static final int SERVICENAME_FIELD_NUMBER = 2;
    private boolean hasServiceName;
    private java.lang.String serviceName_ = "";
    public boolean hasServiceName() { return hasServiceName; }
    public java.lang.String getServiceName() { return serviceName_; }
    
    // optional string methodName = 3;
    public static final int METHODNAME_FIELD_NUMBER = 3;
    private boolean hasMethodName;
    private java.lang.String methodName_ = "";
    public boolean hasMethodName() { return hasMethodName; }
    public java.lang.String getMethodName() { return methodName_; }
    
    // optional bytes requestBytes = 4;
    public static final int REQUESTBYTES_FIELD_NUMBER = 4;
    private boolean hasRequestBytes;
    private com.google.protobuf.ByteString requestBytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasRequestBytes() { return hasRequestBytes; }
    public com.google.protobuf.ByteString getRequestBytes() { return requestBytes_; }
    
    // optional bytes remoteFunction = 5;
    public static final int REMOTEFUNCTION_FIELD_NUMBER = 5;
    private boolean hasRemoteFunction;
    private com.google.protobuf.ByteString remoteFunction_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasRemoteFunction() { return hasRemoteFunction; }
    public com.google.protobuf.ByteString getRemoteFunction() { return remoteFunction_; }
    
    // repeated bytes remoteFunctionDependsClasses = 6;
    public static final int REMOTEFUNCTIONDEPENDSCLASSES_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> remoteFunctionDependsClasses_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getRemoteFunctionDependsClassesList() {
      return remoteFunctionDependsClasses_;
    }
    public int getRemoteFunctionDependsClassesCount() { return remoteFunctionDependsClasses_.size(); }
    public com.google.protobuf.ByteString getRemoteFunctionDependsClasses(int index) {
      return remoteFunctionDependsClasses_.get(index);
    }
    
    private void initFields() {
      requestType_ = balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType.RUN_SERVICE_CALL;
    }
    public final boolean isInitialized() {
      if (!hasRequestType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequestType()) {
        output.writeEnum(1, getRequestType().getNumber());
      }
      if (hasServiceName()) {
        output.writeString(2, getServiceName());
      }
      if (hasMethodName()) {
        output.writeString(3, getMethodName());
      }
      if (hasRequestBytes()) {
        output.writeBytes(4, getRequestBytes());
      }
      if (hasRemoteFunction()) {
        output.writeBytes(5, getRemoteFunction());
      }
      for (com.google.protobuf.ByteString element : getRemoteFunctionDependsClassesList()) {
        output.writeBytes(6, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequestType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getRequestType().getNumber());
      }
      if (hasServiceName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getServiceName());
      }
      if (hasMethodName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getMethodName());
      }
      if (hasRequestBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRequestBytes());
      }
      if (hasRemoteFunction()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRemoteFunction());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getRemoteFunctionDependsClassesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getRemoteFunctionDependsClassesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest result;
      
      // Construct using balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest();
        return builder;
      }
      
      protected balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.getDescriptor();
      }
      
      public balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest getDefaultInstanceForType() {
        return balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.remoteFunctionDependsClasses_ != java.util.Collections.EMPTY_LIST) {
          result.remoteFunctionDependsClasses_ =
            java.util.Collections.unmodifiableList(result.remoteFunctionDependsClasses_);
        }
        balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest) {
          return mergeFrom((balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest other) {
        if (other == balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasServiceName()) {
          setServiceName(other.getServiceName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasRequestBytes()) {
          setRequestBytes(other.getRequestBytes());
        }
        if (other.hasRemoteFunction()) {
          setRemoteFunction(other.getRemoteFunction());
        }
        if (!other.remoteFunctionDependsClasses_.isEmpty()) {
          if (result.remoteFunctionDependsClasses_.isEmpty()) {
            result.remoteFunctionDependsClasses_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.remoteFunctionDependsClasses_.addAll(other.remoteFunctionDependsClasses_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType value = balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setRequestType(value);
              }
              break;
            }
            case 18: {
              setServiceName(input.readString());
              break;
            }
            case 26: {
              setMethodName(input.readString());
              break;
            }
            case 34: {
              setRequestBytes(input.readBytes());
              break;
            }
            case 42: {
              setRemoteFunction(input.readBytes());
              break;
            }
            case 50: {
              addRemoteFunctionDependsClasses(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required .balmysundaycandy.scalatool.shared.CallRequest.RequestType requestType = 1;
      public boolean hasRequestType() {
        return result.hasRequestType();
      }
      public balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType getRequestType() {
        return result.getRequestType();
      }
      public Builder setRequestType(balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRequestType = true;
        result.requestType_ = value;
        return this;
      }
      public Builder clearRequestType() {
        result.hasRequestType = false;
        result.requestType_ = balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.RequestType.RUN_SERVICE_CALL;
        return this;
      }
      
      // optional string serviceName = 2;
      public boolean hasServiceName() {
        return result.hasServiceName();
      }
      public java.lang.String getServiceName() {
        return result.getServiceName();
      }
      public Builder setServiceName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceName = true;
        result.serviceName_ = value;
        return this;
      }
      public Builder clearServiceName() {
        result.hasServiceName = false;
        result.serviceName_ = getDefaultInstance().getServiceName();
        return this;
      }
      
      // optional string methodName = 3;
      public boolean hasMethodName() {
        return result.hasMethodName();
      }
      public java.lang.String getMethodName() {
        return result.getMethodName();
      }
      public Builder setMethodName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMethodName = true;
        result.methodName_ = value;
        return this;
      }
      public Builder clearMethodName() {
        result.hasMethodName = false;
        result.methodName_ = getDefaultInstance().getMethodName();
        return this;
      }
      
      // optional bytes requestBytes = 4;
      public boolean hasRequestBytes() {
        return result.hasRequestBytes();
      }
      public com.google.protobuf.ByteString getRequestBytes() {
        return result.getRequestBytes();
      }
      public Builder setRequestBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRequestBytes = true;
        result.requestBytes_ = value;
        return this;
      }
      public Builder clearRequestBytes() {
        result.hasRequestBytes = false;
        result.requestBytes_ = getDefaultInstance().getRequestBytes();
        return this;
      }
      
      // optional bytes remoteFunction = 5;
      public boolean hasRemoteFunction() {
        return result.hasRemoteFunction();
      }
      public com.google.protobuf.ByteString getRemoteFunction() {
        return result.getRemoteFunction();
      }
      public Builder setRemoteFunction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRemoteFunction = true;
        result.remoteFunction_ = value;
        return this;
      }
      public Builder clearRemoteFunction() {
        result.hasRemoteFunction = false;
        result.remoteFunction_ = getDefaultInstance().getRemoteFunction();
        return this;
      }
      
      // repeated bytes remoteFunctionDependsClasses = 6;
      public java.util.List<com.google.protobuf.ByteString> getRemoteFunctionDependsClassesList() {
        return java.util.Collections.unmodifiableList(result.remoteFunctionDependsClasses_);
      }
      public int getRemoteFunctionDependsClassesCount() {
        return result.getRemoteFunctionDependsClassesCount();
      }
      public com.google.protobuf.ByteString getRemoteFunctionDependsClasses(int index) {
        return result.getRemoteFunctionDependsClasses(index);
      }
      public Builder setRemoteFunctionDependsClasses(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.remoteFunctionDependsClasses_.set(index, value);
        return this;
      }
      public Builder addRemoteFunctionDependsClasses(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.remoteFunctionDependsClasses_.isEmpty()) {
          result.remoteFunctionDependsClasses_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.remoteFunctionDependsClasses_.add(value);
        return this;
      }
      public Builder addAllRemoteFunctionDependsClasses(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.remoteFunctionDependsClasses_.isEmpty()) {
          result.remoteFunctionDependsClasses_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.remoteFunctionDependsClasses_);
        return this;
      }
      public Builder clearRemoteFunctionDependsClasses() {
        result.remoteFunctionDependsClasses_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:balmysundaycandy.scalatool.shared.CallRequest)
    }
    
    static {
      defaultInstance = new CallRequest(true);
      balmysundaycandy.scalatool.shared.RemoteCallRequest.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:balmysundaycandy.scalatool.shared.CallRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_balmysundaycandy_scalatool_shared_CallRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_balmysundaycandy_scalatool_shared_CallRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027RemoteCallRequest.proto\022!balmysundayca" +
      "ndy.scalatool.shared\"\225\002\n\013CallRequest\022O\n\013" +
      "requestType\030\001 \002(\0162:.balmysundaycandy.sca" +
      "latool.shared.CallRequest.RequestType\022\023\n" +
      "\013serviceName\030\002 \001(\t\022\022\n\nmethodName\030\003 \001(\t\022\024" +
      "\n\014requestBytes\030\004 \001(\014\022\026\n\016remoteFunction\030\005" +
      " \001(\014\022$\n\034remoteFunctionDependsClasses\030\006 \003" +
      "(\014\"8\n\013RequestType\022\024\n\020RUN_SERVICE_CALL\020\000\022" +
      "\023\n\017RUN_REMOTE_CALL\020\001B8\n!balmysundaycandy" +
      ".scalatool.sharedB\021RemoteCallRequestH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_balmysundaycandy_scalatool_shared_CallRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_balmysundaycandy_scalatool_shared_CallRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_balmysundaycandy_scalatool_shared_CallRequest_descriptor,
              new java.lang.String[] { "RequestType", "ServiceName", "MethodName", "RequestBytes", "RemoteFunction", "RemoteFunctionDependsClasses", },
              balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.class,
              balmysundaycandy.scalatool.shared.RemoteCallRequest.CallRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
